PlatformAgents/com/cognizant/devops/platformagents/agents/alm/rally/RallyAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/alm/rally/config.json, PlatformAgents/com/cognizant/devops/platformagents/core/BaseAgent.py, PlatformAgents/com/cognizant/devops/platformagents/core/RestCommunicationFacade.py
Following are the changes:
Objective - Rally agent to operate under proxy environment
Config.json - Added proxy and accesstoken key (22&24)
RallyAgent.py-Added headers,proxies and accesstoken(28,33,42-49,51)
core/RestCommunicationFacade.py - Added proxy argument to communicate method and also to get&post call (35,49,51)
BaseAgent.py- Added proxy argument to getResponse method (199,200)
=> Rallyagent

PlatformInsights/pom.xml, PlatformInsights/src/main/java/com/cognizant/devops/platforminsights/core/count/CountActionImpl.java
Had to change pom.xml as well as one very minor change in Java code.
=> Elasticsearch server migration impact changes.

PlatformAgents/com/cognizant/devops/platformagents/agents/DummyDataAgent/createDummyData/DummyDataAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/DummyDataAgent/createDummyData/config.json
Dummy Agent added for bulk data upload.
=> Adding new Agent to generate Dummy Data

Deployment/RHEL7/reference-DocRoot-Scripts/insights_apache.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/codequality/sonar/SonarAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/codequality/sonar/config.json
Sonar agent updated config for alert status and agent file with Project name for better filtering
=> Kp sonar enhancements

PlatformAgents/com/cognizant/devops/platformagents/agents/codequality/sonar/SonarAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/codequality/sonar/config.json, PlatformCommons/src/main/resources/server-config.json
Changes-
1) ServerConfig - Json - by default enabling native users and http for grafana by default
2) Sonar Agent - Added support for accepting credentials..
=> Sonar creds

PlatformGrafanaPlugins/Panels/grafana-piechart-panel/piechart_ctrl.js, PlatformGrafanaPlugins/Panels/insightsviz/editor.ts, PlatformGrafanaPlugins/Panels/multivaluespanel/editor.js, PlatformGrafanaPlugins/Panels/multivaluespanel/editor.ts, PlatformGrafanaPlugins/Panels/panel-skeleton/editor.ts, PlatformGrafanaPlugins/Panels/pipeline/editor.js, PlatformGrafanaPlugins/Panels/pipeline/editor.ts, PlatformGrafanaPlugins/Panels/singlestatneo/editor.js, PlatformGrafanaPlugins/Panels/singlestatneo/editor.ts, PlatformGrafanaPlugins/Panels/singlestattotal/editor.ts, PlatformGrafanaPlugins/Panels/singlestatunique/editor.ts, PlatformGrafanaPlugins/Panels/traceability/editor.ts, PlatformGrafanaPlugins/Panels/traceability/module.ts, PlatformGrafanaPlugins/ScriptedDashboard/iSight.js, README.md
This branch consists of changes for Tracebility plugin images path issue, and Grafana 4.6.2 navigation icon fixes.
=> Grafana bugfix

Jenkinsfile
Apache License Check in javaand Python files
=> Apache License Check in javaand Python files

PlatformAgents/com/cognizant/devops/platformagents/agents/codequality/sonar/SonarAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/codequality/sonar/config.json
Merging Sonar agent for timemachine api and history api versions.
=> Sonar agent

PlatformDAL/src/main/java/com/cognizant/devops/platformdal/config/PlatformDALSessionFactoryProvider.java, PlatformDAL/src/main/java/com/cognizant/devops/platformdal/icon/Icon.java, PlatformDAL/src/main/java/com/cognizant/devops/platformdal/icon/IconDAL.java, PlatformService/src/main/java/com/cognizant/devops/platformservice/rest/customSettings/CustomAppSettings.java, PlatformService/src/main/java/com/cognizant/devops/platformservice/rest/customSettings/ImageResponse.java, PlatformService/src/main/java/com/cognizant/devops/platformservice/security/config/SecurityConfig.java, PlatformUI2.0/app/src/boot.ts, PlatformUI2.0/app/src/modules/appSettings/controller/appSettingsController.ts, PlatformUI2.0/app/src/modules/appSettings/service/appSettingsService.ts, PlatformUI2.0/app/src/modules/appSettings/view/appSettingsView.html, PlatformUI2.0/app/src/modules/homepage/controller/homePageController.ts, PlatformUI2.0/app/src/modules/homepage/view/homePageView.html, PlatformUI2.0/app/src/modules/login/controller/loginController.ts, PlatformUI2.0/app/src/modules/login/view/loginView.html, PlatformUI2.0/app/src/modules/restAPIUrl/service/resAPIUrlService.ts
=> logo changes

PlatformAgents/com/cognizant/devops/platformagents/agents/ci/CircleAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/ci/config.json
Circle CI agent first cut version only. This needs to be extended for enterprise usage.
=> CircleCI Agent version 1

PlatformUI2.0/app/src/modules/restAPIUrl/service/resAPIUrlService.ts
=> DefectFix3.7

Deployment/RHEL7/reference-DocRoot-Scripts/insights_enginejar.sh, Deployment/RHEL7/reference-DocRoot-Scripts/insights_python.sh, Deployment/RHEL7/reference-DocRoot-Scripts/insights_tomcat8.sh
Insights artifacts location update in shell scripts
=> Insights artifacts location update in shell scripts

DbBackup/neo4j_export.py, DbBackup/neo4j_label_list.json, PlatformAgents/com/cognizant/devops/platformagents/agents/alm/pivotalTracker/InSightsPivotalTrackerAgent.service, PlatformAgents/com/cognizant/devops/platformagents/agents/alm/pivotalTracker/InSightsPivotalTrackerAgent.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/alm/pivotalTracker/PivotalTrackerAgent.bat, PlatformAgents/com/cognizant/devops/platformagents/agents/alm/pivotalTracker/PivotalTrackerAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/alm/pivotalTracker/config.json, PlatformAgents/com/cognizant/devops/platformagents/agents/alm/pivotalTracker/installagent.bat, PlatformAgents/com/cognizant/devops/platformagents/agents/alm/pivotalTracker/installagent.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/artifactmanagement/artifactory/ArtifactoryAgent.bat, PlatformAgents/com/cognizant/devops/platformagents/agents/artifactmanagement/artifactory/ArtifactoryAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/artifactmanagement/artifactory/InSightsArtifactoryAgent.service, PlatformAgents/com/cognizant/devops/platformagents/agents/artifactmanagement/artifactory/InSightsArtifactoryAgent.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/artifactmanagement/artifactory/config.json, PlatformAgents/com/cognizant/devops/platformagents/agents/artifactmanagement/artifactory/installagent.bat, PlatformAgents/com/cognizant/devops/platformagents/agents/artifactmanagement/artifactory/installagent.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/ci/concourse/ConcourseAgent.bat, PlatformAgents/com/cognizant/devops/platformagents/agents/ci/concourse/ConcourseAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/ci/concourse/InSightsConcourseAgent.service, PlatformAgents/com/cognizant/devops/platformagents/agents/ci/concourse/InSightsConcourseAgent.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/ci/concourse/config.json, PlatformAgents/com/cognizant/devops/platformagents/agents/ci/concourse/installagent.bat, PlatformAgents/com/cognizant/devops/platformagents/agents/ci/concourse/installagent.sh, PlatformService/src/main/java/com/cognizant/devops/platformservice/rest/AccessGroupManagement/AccessGroupManagement.java, PlatformService/src/main/java/com/cognizant/devops/platformservice/security/config/GrafanaUserDetailsUtil.java, PlatformUI2.0/app/src/modules/homepage/controller/homePageController.ts
Adding Pythin Agents for Concourse, Pivotal Tracker, Artifactory
Added neo4j database backup scripts
=> Python agents

Deployment/RHEL7/reference-DocRoot-Scripts/insights_agents.sh
=> Updating the script for Daemon agent as per Agent2.0 architecture

PlatformUI2.0/app/src/modules/agent/controller/uninstallAgentDialogController.ts
1) Agent uninstall page refresh issue
=> Agents2.0 Enhancement - Changed sequence of service call

PlatformUI2.0/app/src/modules/agent/controller/uninstallAgentDialogController.ts, PlatformUI2.0/app/src/modules/homepage/view/homePageView.html
Updates-
1. Changed About Insights pointing link
2. Changed default Admin tab's landing page as "Access Group Management"
3. Resolved formatting issues.
=> Agent2.0 enhancements

PlatformAgents/com/cognizant/devops/platformagents/core/MessageQueueProvider.py, PlatformService/src/main/java/com/cognizant/devops/platformservice/agentmanagement/service/AgentManagementServiceImpl.java
- Create DATA and HEALTH queues without Engine being running
- Db operation after MQ operation is over
=> Agent20 patch

Deployment/RHEL7/reference-DocRoot-Scripts/insights_first.sh
Removed additional package under INSIGHTS_HOME
=> Updated install_first Script 

Deployment/RHEL7/reference-DocRoot-Scripts/insights_first.sh, Deployment/RHEL7/reference-DocRoot-Scripts/insights_tomcat8.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/agentdaemon/config.json, PlatformService/src/main/java/com/cognizant/devops/platformservice/config/InsightsConfiguration.java
updated tomcat 8 script for getting app folder under webapps
updated insights first script for setting up permissions
commenting updateLayouts as its longer needed
updating the script to identofy the external ip and replace in server config json
updating agent daemon config json for extraction path and default MQ password
=> Scriptupdates

PlatformService/src/main/java/com/cognizant/devops/platformservice/agentmanagement/controller/InsightsAgentConfiguration.java, PlatformService/src/main/java/com/cognizant/devops/platformservice/agentmanagement/service/AgentManagementService.java, PlatformService/src/main/java/com/cognizant/devops/platformservice/agentmanagement/service/AgentManagementServiceImpl.java, PlatformUI2.0/app/src/modules/agent/controller/agenListController.ts, PlatformUI2.0/app/src/modules/agent/controller/agentManagementController.ts, PlatformUI2.0/app/src/modules/agent/service/agentService.ts, PlatformUI2.0/app/src/modules/agent/view/agentManagementView.html, PlatformUI2.0/app/src/modules/homepage/controller/homePageController.ts
1. Functionality to upload existing tracking.json to help upgrade  Insights product to latest version
=> Agents2.0 tracking json upload feature

Deployment/RHEL7/reference-DocRoot-Scripts/insights_agents.sh, Deployment/RHEL7/reference-DocRoot-Scripts/insights_enginejar.sh, Deployment/RHEL7/reference-DocRoot-Scripts/insights_first.sh, Deployment/RHEL7/reference-DocRoot-Scripts/insights_tomcat8.sh
Fixed scripts for auto installation of Agent Daemon, copying on InsightUI and commented updatelayout code which is not required after Agent2.0
=> Updating scripts for agents, engine, first, tomcat

Deployment/RHEL7/reference-DocRoot-Scripts/insights_python.sh
updating python install script
=> Udating Python Install Scripts

PlatformAgents/com/cognizant/devops/platformagents/agents/alm/rally/RallyAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/alm/rally/config.json
RallyAgent Updation :
Added Duplicate reduction logic and optimized the code and compatible with Agent2.0.
=> Python-RallyAgent Enhancement

PlatformCommons/src/main/java/com/cognizant/devops/platformcommons/dal/elasticsearch/ElasticSearchDBHandler.java, PlatformCommons/src/main/resources/server-config.json, PlatformService/src/main/java/com/cognizant/devops/platformservice/rest/querycaching/service/QueryCachingConstants.java, PlatformService/src/main/java/com/cognizant/devops/platformservice/rest/querycaching/service/QueryCachingServiceImpl.java, PlatformUI2.0/app/src/modules/agent/controller/agentManagementController.ts, PlatformUI2.0/app/src/modules/homepage/controller/homePageController.ts, PlatformUI2.0/app/uiConfig.json
This branch contains changes of Agents2.0, and Query Caching. The list of the changes/features are:
1. Add custom OS list for Agents2.0 configuration.
2. Changes in Query Caching mechanism to handle ES error 404, and publish results at default index.
=> Agent2.0 os fixes

PlatformEngine/src/main/java/com/cognizant/devops/platformengine/modules/offlinedataprocessing/OfflineDataProcessingExecutor.java
Code changes done to fix the error and as per review comment.
=> Offlineproduct360

PlatformAgents/com/cognizant/devops/platformagents/agents/scm/gitlab/GitLabAgent.bat, PlatformAgents/com/cognizant/devops/platformagents/agents/scm/gitlab/GitLabAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/scm/gitlab/InSightsGitLabAgent.service, PlatformAgents/com/cognizant/devops/platformagents/agents/scm/gitlab/InSightsGitLabAgent.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/scm/gitlab/config.json, PlatformAgents/com/cognizant/devops/platformagents/agents/scm/gitlab/installagent.bat, PlatformAgents/com/cognizant/devops/platformagents/agents/scm/gitlab/installagent.sh, PlatformService/pom.xml
Adding Gitlab-SCM agent to pull data from gitlab with commit details, branch details and removing duplication logic in neo4j.
=> Git lab agent

Deployment/RHEL7/initscripts/Grafana.sh, Deployment/RHEL7/initscripts/InSightsEngine.sh, Deployment/RHEL7/initscripts/InSightsGitAgent.sh, Deployment/RHEL7/initscripts/Neo4j.sh, Deployment/RHEL7/initscripts/Tomcat8.sh, Deployment/RHEL7/reference-DocRoot-Scripts/insights_first.sh, Deployment/RHEL7/reference-DocRoot-Scripts/insights_java.sh, PlatformUI2.0/app/src/modules/agent/view/agentManagementView.html, PlatformUI2.0/app/uiConfig.json
Agent Management files changes to show OS version as 'Windows','RHFL','CentOS'. 
Modified initscript to support CentOS and RHEL.
Test script for CentOS Linux operating system flavor
=> CentOS Installation 

Deployment/RHEL7/initscripts/Grafana.sh, Deployment/RHEL7/initscripts/InSightsEngine.sh, Deployment/RHEL7/initscripts/InSightsGitAgent.sh, Deployment/RHEL7/initscripts/Neo4j.sh, Deployment/RHEL7/initscripts/Tomcat8.sh
Added Apache Licence 2.0 in shell scripts
=> Production Bug Fixes - Added Licence Test In Init Shell Scripts

PlatformAgents/com/cognizant/devops/platformagents/agents/alm/hp/HpAlmAgent.py, PlatformAgents/com/cognizant/devops/platformagents/agents/alm/jira/JiraAgent.py, PlatformAgents/com/cognizant/devops/platformagents/core/RestCommunicationFacade.py
Fixing following issues:
- Fixed change history integration
- Fixed HP-ALM agent to extend session and to use domains from configurations if specified.
=> Jira Agent and HP Alm agent fixes

PlatformAgents/com/cognizant/devops/platformagents/agents/alm/pivotalTracker/PivotalTrackerAgent.py
Code changes done to fix compilation issue in PivotalTracker Agent
=> Fixed compilation issue in PivotalTracker Agent

Deployment/RHEL7/initscripts/Grafana5.sh, Deployment/RHEL7/reference-DocRoot-Scripts/insights_grafana5.sh
RHEL script changes for grafana5
=> Grafana v5.0 upgrade

PlatformUI2.0/app/uiConfig.json
Changes in UI config to support CentOS
=> Changes in UI config to support CentOS

PlatformAgents/com/cognizant/devops/platformagents/agents/alm/pivotalTracker/installagent.bat, PlatformAgents/com/cognizant/devops/platformagents/agents/alm/pivotalTracker/installagent.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/artifactmanagement/artifactory/installagent.bat, PlatformAgents/com/cognizant/devops/platformagents/agents/artifactmanagement/artifactory/installagent.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/ci/concourse/installagent.bat, PlatformAgents/com/cognizant/devops/platformagents/agents/ci/concourse/installagent.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/ci/jenkins/installagent.sh, PlatformAgents/com/cognizant/devops/platformagents/agents/codequality/sonar/installagent.sh
Fixing bugs in installagent.sh script to be compatible with Agent 2.0 structure.
=> Agent2.0 script sh issue fix

PlatformGrafanaPlugins/Panels/grafana-piechart-panel/package.json, PlatformGrafanaPlugins/Panels/grafana-singlestat-totalcount/package.json, PlatformGrafanaPlugins/Panels/grafana-singlestat-uniquecount/package.json
Updating node modules dependency in Grafana panels to remove GitHub Security Issues.
=> Git security fix

PlatformDeployment/InSightsDiagnosis/server_check.sh
Created a automated script to read the server config and validate the necessary values which are present in it
=> Added server_check.sh

Jenkinsfile
updated Jenkinsfile in versionManagement
=> Version management

PlatformDeployment/InSightsDiagnosis/preRequisite.sh
Fixing https in shell script file.
=> Fixing https in InSightsDiagnosis.

PlatformCommons/pom.xml
Hot Fix for security vulnerability issue  in jetty-http package version 8.1.12.
=>  #162085954 Adding security related changes in pom file.

PlatformEngine/src/main/java/com/cognizant/devops/platformengine/modules/offlinedataprocessing/OfflineDataProcessingExecutor.java, PlatformEngine/src/main/java/com/cognizant/devops/platformengine/modules/offlinedataprocessing/model/DataEnrichmentModel.java, PlatformEngine/src/test/java/com/cognizant/devops/platformengine/modules/offlinedataprocessing/OfflineDataProcessingExecutorTest.java
Adding support for providing cron schedule in offline processing - data enrichment JSON.
=> Adding support for CRON schedule in offline processing.

PlatformGrafanaPlugins/Panels/Vonage_Status_panel/package.json
Fixing security violation issue in status panel package json.
=> Fixing security violation issue in status panel package json.

PlatformAgents/com/cognizant/devops/platformagents/core/BaseAgent.py, PlatformCommons/src/main/java/com/cognizant/devops/platformcommons/core/util/ComponentHealthLogger.java, PlatformCommons/src/main/java/com/cognizant/devops/platformcommons/core/util/InsightsUtils.java, PlatformUI3/src/app/com/cognizant/devops/platformui/common.services/data-shared-service.ts, PlatformUI3/src/app/com/cognizant/devops/platformui/login/login.component.ts, PlatformUI3/src/app/com/cognizant/devops/platformui/modules/healthcheck/healthcheck-show-details-dialog.ts, PlatformUI3/src/app/com/cognizant/devops/platformui/modules/healthcheck/healthcheck.component.html, PlatformUI3/src/app/com/cognizant/devops/platformui/modules/healthcheck/healthcheck.component.ts
=> #162193047 "Date Format Code"

PlatformAgents/com/cognizant/devops/platformagents/agents/alm/rally/RallyAgent.py
166115065  Rally Agent modification for additional field and resolved some issue
=> Rally Agent modification
